# Generated by Django 4.2.9 on 2024-03-12 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertype',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
