# Generated by Django 4.2.10 on 2024-03-05 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingCalc',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_id', models.CharField(editable=False, max_length=10, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'ذرعات البنايات',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, unique=True)),
                ('total_dinar', models.FloatField()),
                ('total_dollar', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'المشاريع',
            },
        ),
        migrations.CreateModel(
            name='CompanyType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'انواع المشاريع',
            },
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('total_dinar', models.FloatField()),
                ('total_dollar', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'القاصات',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_id', models.CharField(editable=False, max_length=10, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'الفواتير',
            },
        ),
        migrations.CreateModel(
            name='WithdrawType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'القيود',
            },
        ),
        migrations.CreateModel(
            name='WorkerCalc',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_id', models.CharField(editable=False, max_length=10, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'ذرعات الخلفات',
            },
        ),
        migrations.CreateModel(
            name='Withdraw',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_id', models.CharField(editable=False, max_length=10, unique=True)),
                ('price_in_dinar', models.FloatField()),
                ('price_in_dollar', models.FloatField()),
                ('description', models.TextField(max_length=2000)),
                ('out_to', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField()),
                ('record_created_at', models.DateTimeField(auto_now=True)),
                ('withdraw_number', models.PositiveIntegerField(blank=True, unique=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='withdraw_documents/')),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mms_api.company')),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mms_api.container')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by_withdrawer', to=settings.AUTH_USER_MODEL)),
                ('withdraw_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mms_api.withdrawtype')),
            ],
            options={
                'verbose_name_plural': 'الصرفيات',
            },
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, unique=True)),
                ('total_dinar', models.FloatField()),
                ('total_dollar', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mms_api.container')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'خاص',
            },
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_id', models.CharField(editable=False, max_length=10, unique=True)),
                ('price_in_dinar', models.FloatField()),
                ('price_in_dollar', models.FloatField()),
                ('description', models.TextField(max_length=2000)),
                ('received_from', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField()),
                ('record_created_at', models.DateTimeField(auto_now=True)),
                ('deposit_number', models.PositiveIntegerField(blank=True, unique=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='withdraw_documents/')),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mms_api.company')),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mms_api.container')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'الايداعات',
            },
        ),
        migrations.AddField(
            model_name='company',
            name='company_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mms_api.companytype'),
        ),
        migrations.AddField(
            model_name='company',
            name='container',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mms_api.container'),
        ),
        migrations.AddField(
            model_name='company',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='company',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisor', to=settings.AUTH_USER_MODEL),
        ),
    ]
