# Generated by Django 4.2.10 on 2024-03-05 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mms_api', '0003_paymentcycle_rename_cycle_vendor_payment_cycle_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyType',
        ),
        migrations.AddField(
            model_name='payment',
            name='vendor_name',
            field=models.CharField(default='test', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
