# Generated by Django 4.2.10 on 2024-03-05 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mms_api', '0004_delete_companytype_payment_vendor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mms_api.paymentcycle'),
        ),
    ]
