# Generated by Django 4.2.10 on 2024-03-05 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mms_api', '0008_alter_payment_date_from_alter_payment_date_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.FloatField(max_length=255),
        ),
        migrations.AlterField(
            model_name='payment',
            name='number',
            field=models.IntegerField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='payment',
            name='vendor_id',
            field=models.IntegerField(unique=True),
        ),
    ]
