# Generated by Django 4.2.10 on 2024-03-05 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mms_api', '0009_alter_payment_amount_alter_payment_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='number',
            field=models.IntegerField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='payment_cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mms_api.paymentcycle'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mms_api.paymentmethod'),
        ),
    ]
