# Generated by Django 4.2.10 on 2024-03-05 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mms_api', '0010_alter_vendor_number_alter_vendor_payment_cycle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paidorders',
            name='amount',
            field=models.FloatField(max_length=255),
        ),
    ]
