# Generated by Django 4.2.10 on 2024-03-05 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mms_api', '0011_alter_paidorders_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='account_manager',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='account_manager', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
