# Generated by Django 4.2.9 on 2024-03-10 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mms_api', '0012_vendor_account_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='number',
            field=models.IntegerField(blank=True),
        ),
    ]
