# Generated by Django 4.2.9 on 2024-03-10 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mms_api', '0013_alter_payment_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='vendor_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='vendor_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vendor_id',
            field=models.CharField(max_length=255),
        ),
    ]
