# Generated by Django 4.2.9 on 2024-03-13 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mms_api', '0015_rename_payment_cycle_vendor_pay_period_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='number',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
