# Generated by Django 4.2.9 on 2024-03-14 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mms_api', '0016_alter_vendor_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paidorders',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='paidorders',
            name='paid',
        ),
        migrations.AddField(
            model_name='paidorders',
            name='cancellation_reason',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paidorders',
            name='cancellation_type',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paidorders',
            name='commission_percentage',
            field=models.FloatField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paidorders',
            name='commission_value',
            field=models.FloatField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paidorders',
            name='hybrid_payment',
            field=models.FloatField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paidorders',
            name='lastStatus',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paidorders',
            name='order_date',
            field=models.DateTimeField(default='2024-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paidorders',
            name='refund',
            field=models.FloatField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paidorders',
            name='sub_total',
            field=models.FloatField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paidorders',
            name='to_be_paid',
            field=models.FloatField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paidorders',
            name='total_discount',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paidorders',
            name='vendor',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paidorders',
            name='vendor_discount',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paidorders',
            name='vendor_discount_cap',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paidorders',
            name='vendor_id',
            field=models.ForeignKey(default=492, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_db_id', to='mms_api.vendor'),
            preserve_default=False,
        ),
    ]
