# Generated by Django 4.2.9 on 2024-03-14 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mms_api', '0017_remove_paidorders_amount_remove_paidorders_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paidorders',
            name='payment_id',
            field=models.CharField(editable=False, max_length=10, unique=True),
        ),
    ]
