# Generated by Django 4.2.9 on 2024-03-17 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mms_api', '0019_payment_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='orders',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
