# Generated by Django 4.2.9 on 2024-03-17 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mms_api', '0020_payment_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='number',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
