# Generated by Django 4.2.9 on 2024-03-17 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mms_api', '0021_alter_payment_amount_alter_payment_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.CharField(max_length=255),
        ),
    ]
