# Generated by Django 4.2.9 on 2024-03-17 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mms_api', '0023_rename_vendor_name_payment_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='orders_count',
            field=models.JSONField(default=9),
            preserve_default=False,
        ),
    ]
