# Generated by Django 4.2.9 on 2024-03-25 19:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mms_api', '0025_alter_payment_payment_cycle_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='date_from',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='orders_count',
            new_name='order_count',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='amount',
            new_name='pay_period',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='payment_cycle',
            new_name='pay_type',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='date_to',
            new_name='start_date',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='payment_method',
            new_name='to_be_paid',
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
