# Generated by Django 4.2.9 on 2024-03-26 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mms_api', '0026_rename_date_from_payment_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='vendor_id',
            field=models.IntegerField(),
        ),
    ]
