# Generated by Django 4.2.9 on 2024-04-03 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mms_api', '0029_remove_feedback_clean_level_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='client_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
