# Generated by Django 4.2.10 on 2024-04-07 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mms_api', '0030_alter_feedback_client_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='client_number',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
